-- Update recepcion_productos table with new columns
ALTER TABLE public.recepcion_productos 
ADD COLUMN IF NOT EXISTS proveedor text,
ADD COLUMN IF NOT EXISTS guia_factura text,
ADD COLUMN IF NOT EXISTS temperatura_transporte numeric,
ADD COLUMN IF NOT EXISTS condicion_higienica text,
ADD COLUMN IF NOT EXISTS indumentaria_limpia text,
ADD COLUMN IF NOT EXISTS higiene_personal text,
ADD COLUMN IF NOT EXISTS ubicacion text,
ADD COLUMN IF NOT EXISTS lote text,
ADD COLUMN IF NOT EXISTS ph numeric,
ADD COLUMN IF NOT EXISTS aspecto_fisico text,
ADD COLUMN IF NOT EXISTS color text,
ADD COLUMN IF NOT EXISTS olor text,
ADD COLUMN IF NOT EXISTS hermeticidad text,
ADD COLUMN IF NOT EXISTS libre_impurezas text,
ADD COLUMN IF NOT EXISTS estado_envase text,
ADD COLUMN IF NOT EXISTS conclusiones text,
ADD COLUMN IF NOT EXISTS inspeccion_calidad boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS pallets numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS cajas numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS unidades numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS unidad_medida text,
ADD COLUMN IF NOT EXISTS autorizado_por text;
